#!/usr/bin/env bash
# Generates lib/config/firebase_secrets.dart from native Firebase config files.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/lib/config/firebase_secrets.dart"
PLIST="$ROOT/ios/Runner/GoogleService-Info.plist"
JSON="$ROOT/android/app/google-services.json"

if [[ ! -f "$PLIST" ]]; then
  echo "Missing $PLIST"
  exit 1
fi
if [[ ! -f "$JSON" ]]; then
  echo "Missing $JSON"
  exit 1
fi

IOS_CLIENT="$(plutil -extract CLIENT_ID raw -o - "$PLIST")"
WEB_CLIENT="$(python3 - "$JSON" <<'PY'
import json, sys
data = json.load(open(sys.argv[1]))
clients = data["client"][0]["oauth_client"]
web = next(c["client_id"] for c in clients if c.get("client_type") == 3)
print(web)
PY
)"

cat > "$OUT" <<EOF
/// Generated by scripts/setup_firebase_secrets.sh — do not commit.
abstract final class FirebaseSecrets {
  static const googleWebClientId = '$WEB_CLIENT';
  static const googleIosClientId = '$IOS_CLIENT';
}
EOF

echo "Wrote $OUT"
